
include(InstallRequiredSystemLibraries)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_VERSION_MAJOR "${hello_world_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${hello_world_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${hello_world_VERSION_PATCH}")
set(CPACK_SOURCE_GENERATOR "TGZ")

include(CPack)